config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/destroy'
  # ! Check plural or singular for users
  devise_for :user, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "kitchens#index"
  resources :kitchens do
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:create]
  end
  get '/dashboard', to: 'pages#dashboard'
  get 'booking/:id/accept', to: 'bookings#accept', as: :accept
  get 'booking/:id/decline', to: 'bookings#decline', as: :decline
  resources :bookings, only: :destroy
  resources :reviews, only: :destroy
end

app/views/pages/dashboard.html.erb
<div class="booking-cofirmation">
<h3>My bookings</h3>
<div class="row ">
    <% @bookings.each do |booking| %>
      <div class="col-md-4">
        <div class="kitchen-card">
            <div class="kitchen-card-title" style="padding: 15px 0px; ">
              <h4><%= booking.kitchen.name %></h4>
            </div>
            <div class="kitchen-card-content" style="margin: 0; ">
              <p>Your booking is on:  <%= booking.date %></p>
              <p>Your booking is:  <%= booking.status %></p>
            </div>
          <div class="kitchen-card-actions">
            <%= link_to 'Cancel reservation', booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "are you sure?" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Logic to Accept / Decline a booking -->
<div class="booking-cofirmation">
<h3>My kitchens</h3>
<div class="row">
    <% @kitchens.each do |kitchen| %>
      <div class="col-md-4">
        <div class="kitchen-card">
          <div class="kitchen-card-image" style="background-image: url('<%= cl_image_path kitchen.photo.key %>')"></div>
          <div class="kitchen-card-content">
            <div class="kitchen-card-title">
              <h4><%= kitchen.name %></h4>
            </div>
            <p><%= kitchen.address %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-people-line"></i>
                <span><%= kitchen.capacity %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <i class="fa-solid fa-euro-sign"></i>
                <span><%= kitchen.price %></span>
              </div>
            </div>
          </div>
          <div class="kitchen-card-actions">
            <%= link_to "Show this kitchen", kitchen_path(kitchen) %>
          </div>
          <div>
          <ul>
            <% kitchen.bookings.each do |booking| %>
              <li>
                <p><%= booking.user.first_name %> wants to book on <%= booking.date %></p>
                <% if booking.status == "pending" %>
                <div class="kitchen-card-actions">
                  <%= link_to "Accept", accept_path(booking) %>
                  <%= link_to "Decline", decline_path(booking) %>
                </div>
                <% elsif booking.status == "accepted" %>
                  <p>The booking was accepted</p>
                  <%= link_to "Decline", decline_path(booking) %>
                <% end %>
              </li>
            <% end %>
          </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>
</div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>