config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/destroy'
  # ! Check plural or singular for users
  devise_for :user, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "kitchens#index"
  resources :kitchens do
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:create]
  end
  get '/dashboard', to: 'pages#dashboard'
  get 'booking/:id/accept', to: 'bookings#accept', as: :accept
  get 'booking/:id/decline', to: 'bookings#decline', as: :decline
  resources :bookings, only: :destroy
  resources :reviews, only: :destroy
end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  include PgSearch::Model
  has_one_attached :photo
  validates :name, :photo, presence: true
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  pg_search_scope :search_by_name_and_address,
  against: [ :name, :address ],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @kitchens = Kitchen.search_by_name_and_address(params[:query])
    else
      @kitchens = Kitchen.all
    end
  end

  def new
    @kitchen = Kitchen.new
  end

  def create
    @kitchen = Kitchen.new(kitchen_params)
    @kitchen.user = current_user
    if @kitchen.save
      redirect_to @kitchen
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
    @marker = {
      lat: @kitchen.latitude,
      lng: @kitchen.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { kitchen: @kitchen }),
      marker_html: render_to_string(partial: "marker", locals: { kitchen: @kitchen })
    }
  end

  def edit
  end

  def update
    if current_user == @kitchen.user
      if @kitchen.update(kitchen_params)
        redirect_to @kitchen, notice: 'Kitchen was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to kitchens_path, alert: 'You are not authorized to update this kitchen.'
    end
  end

  def destroy
    if current_user == @kitchen.user
      @kitchen.destroy
      redirect_to kitchens_path, notice: 'Kitchen was successfully destroyed.'
    else
      redirect_to kitchens_path, alert: 'You are not authorized to perform this action.'
    end
  end

  private

  def set_kitchen
    id = params[:id] ? params[:id] : params[:kitchen_id]
    @kitchen = Kitchen.find(id)
  end

  def kitchen_params
    params.require(:kitchen).permit(:name, :address, :description, :price, :capacity, :photo)
  end
end

app/views/kitchens/_form.html.erb
        <%= simple_form_for @kitchen do |f| %>
          <%= f.input :name, placeholder: 'Name of the Kitchen' %>
          <%= f.input :description, placeholder: 'Description' %>
          <%= f.input :capacity, placeholder: 'Number of guests' %>
          <%= f.input :price, placeholder: 'Price for the renting' %>
          <%= f.input :photo, as: :file %>
          <%= f.input :address,
            input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
            wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
          %>
          <%= f.submit class: 'btn btn-secondary' %>
        <% end %>

app/views/kitchens/_info_window.html.erb
<h2><%= kitchen.name %></h2>
<p><%= kitchen.address %></p>

app/views/kitchens/_marker.html.erb
<%= image_tag "logo.jpg", height: 30, width: 30, alt: "Logo" %>
<div class="badge rounded-pill bg-primary fs-6">
  <%= @kitchen.name %>
</div>

app/views/kitchens/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h2>Edit this kitchen</h2>
        <div class="mt-3">
          <%= render "form", kitchen: @kitchen %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/kitchens/index.html.erb
<div class="container">
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= image_url("banner1.jpg") %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= image_url("banner2.jpg")%>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= image_url("banner3.jpg") %>" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="card-category" style ="color: black; opacity: 0.6">
<%= form_with url: kitchens_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control input",
    placeholder: "Find the best kitchen for yourself...", class: "input"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

</div>
<div class="row">
    <% @kitchens.each do |kitchen| %>
      <div class="col-md-4">
        <div class="kitchen-card">
          <div class="kitchen-card-image" style="background-image: url('<%= cl_image_path kitchen.photo.key if kitchen.photo.key %>')"></div>
          <div class="kitchen-card-content">
            <div class="kitchen-card-title">
              <h4><%= kitchen.name %></h4>
            </div>
            <p><%= kitchen.address %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-people-line"></i>
                <span><%= kitchen.capacity %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <i class="fa-solid fa-euro-sign"></i>
                <span><%= kitchen.price %></span>
              </div>
            </div>
          </div>
          <div class="kitchen-card-actions">
            <%= link_to "Show this kitchen", kitchen_path(kitchen) %>
            <%= link_to "Edit", edit_kitchen_path(kitchen), class: "ms-3 text-warning" %>
            <%= link_to "Remove", kitchen_path(kitchen),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "ms-3 text-danger"
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/kitchens/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h2>Create a new kitchen</h2>
        <div class="mt-3">
          <%= render "form", kitchen: @kitchen %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/kitchens/show.html.erb
<div class="map" style="background-image: url('<%= cl_image_path @kitchen.photo.key %>')"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="kitchen-show-card">
        <h1><%= @kitchen.name %></h1>
        <p class="kitchen-show-address">Address: <%= @kitchen.address %></p>
      </div>
      <div class="kitchen-show-card">
        <h3>A bit more about this kitchen...</h3>
        <p>Description: <%= @kitchen.description %></p>
      </div>
          <div style="width: 100%; height: 600px"
                data-controller="map"
                data-map-marker-value="<%= @marker.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
    </div>

    <div class="col-4">
      <div class="kitchen-show-card">
        <h5>Book <%= @kitchen.name %></h5>
        <%= simple_form_for [@kitchen, @booking] do |f| %>
          <%= f.input :date, placeholder: '09/03/2023', label: "Start Date" %>
          <%= f.input :date, placeholder: '10/03/2023', label: "End Date" %>
          <%= f.submit class: "btn btn-secondary" %>
        <% end %>
      <div class="kitchen-show-card">
        <h4>Details</h4>
        <div class="flex">
          <div class="flex">
            <%= @kitchen.capacity %> people
          </div>
          <div class="flex ms-3">
            <%= @kitchen.price %>€
          </div>
        </div>
      </div>
      <div class="kitchen-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share this kitchen</h6>
          <div class="flex">
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
      <div class="kitchen-show-card">
      <h4>Reviews</h4>
            <% if @kitchen.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this kitchen</em></small>
      <% end %>
      <% @kitchen.reviews.each do |review| %>
        <div>
          <% review.raiting.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
      <h5>Add your review</h5>
        <%= simple_form_for [@kitchen, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :raiting, as: :select, collection: (1..5), required: true, prompt: "What's your rating" %>
          <%= f.submit class:"btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>